language: php

php:
  - 7.3
  - 7.4

before_install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

before_script:
  - cp .env.example .env

script:
  - ./vendor/bin/phpunit --verbose tests/MockTest.php
  - ./vendor/bin/phpunit --verbose tests/SerializeTest.php
  - ./vendor/bin/phpunit --verbose tests/MapperTest.php

jobs:
  include:
    - php: 7.3
      env: TYPE=phpstan
      script:
        - ./vendor/bin/phpstan analyse
    - php: 7.4
      env: TYPE=phpstan
      script:
        - ./vendor/bin/phpstan analyse
